version: "3"
services:
  app:
    container_name: tekever_task1
    image: gstreamer-python:latest
    command: bash -c "tail -f >> /dev/null"
    volumes:
      - ../:/task1
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: host
